using FellowOakDicom;
using FellowOakDicom.Imaging;
using FellowOakDicom.Imaging.Codec;
using FellowOakDicom.PureCodecs.Jpeg2000;
using FellowOakDicom.PureCodecs.Tests.TestSupport;
using System.Security.Cryptography;
using Xunit;

namespace FellowOakDicom.PureCodecs.Tests;

public sealed class Jpeg2000ExternalAcceptanceTests
{
    // Baselines generated by decoding the same Efferent fixtures with fo-dicom.Codecs 5.16.5.1
    // and its bundled Dicom.Native.dll. The PM5644 RGB raw sample is not byte-identical to these
    // JPEG 2000 fixture decodes, so it must not be used as the pixel truth for this test.
    public static TheoryData<string, DicomTransferSyntax, string> Jpeg2000OpenJpegBaselines => new()
    {
        {
            "JPEG 2000 lossless acceptance sample",
            DicomTransferSyntax.JPEG2000Lossless,
            "1d80804ce3bf58f9b2b2171b071c9426469197ec0b772aaa17b7c44d42994224"
        },
        {
            "JPEG 2000 lossy acceptance sample",
            DicomTransferSyntax.JPEG2000Lossy,
            "56dcbb912c849252677e4ab44592fe7ff4b43d3b807bc8052480fe9922b65136"
        },
    };

    [Theory]
    [MemberData(nameof(Jpeg2000OpenJpegBaselines))]
    public void Efferent_jpeg2000_acceptance_samples_match_fo_dicom_codecs_openjpeg_baseline(
        string fixtureName,
        DicomTransferSyntax syntax,
        string expectedFrameSha256)
    {
        var catalog = ExternalFixtureCatalog.Resolve();
        var fixture = catalog.AcceptanceFixtures.Single(item => item.Name == fixtureName);
        Assert.Equal(syntax, fixture.ExpectedTransferSyntax);
        var file = DicomFile.Open(fixture.Path);
        var compressed = DicomPixelData.Create(file.Dataset);
        var rawDataset = CloneForTransferSyntax(file.Dataset, DicomTransferSyntax.ExplicitVRLittleEndian);
        var raw = DicomPixelData.Create(rawDataset, true);
        IDicomCodec codec = syntax == DicomTransferSyntax.JPEG2000Lossless
            ? new DicomJpeg2000LosslessCodec()
            : new DicomJpeg2000LossyCodec();

        codec.Decode(compressed, raw, codec.GetDefaultParameters());

        Assert.Equal(960, (int)raw.Width);
        Assert.Equal(540, (int)raw.Height);
        Assert.Equal(3, (int)raw.SamplesPerPixel);
        Assert.Equal(1, (int)raw.NumberOfFrames);
        Assert.Equal(expectedFrameSha256, Sha256(raw.GetFrame(0).Data));
    }

    private static DicomDataset CloneForTransferSyntax(DicomDataset source, DicomTransferSyntax transferSyntax)
    {
        var clone = new DicomDataset(transferSyntax);
        foreach (var item in source)
        {
            clone.Add(item);
        }

        clone.Remove(DicomTag.PixelData);
        return clone;
    }

    private static string Sha256(byte[] data)
    {
        using var sha256 = SHA256.Create();
        return BitConverter.ToString(sha256.ComputeHash(data)).Replace("-", "").ToLowerInvariant();
    }
}
